package Recursion.SwapNodes;

public class ListNode {

    // this has been generated by chatGPT. not clear to me yet. try to understand, 

    int val;
    ListNode next;

    ListNode(int val) {
        this.val = val;
        this.next = null;
    }
}
